# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

version: "3.6"
services:
  mysqldb:
    image: "$MySqlImageName"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=cromwell_db
    volumes:
      - type: bind
        source: /data/mysql
        target: /var/lib/mysql
      - type: bind
        source: /data/cromwellazure/mysql-init
        target: /mysql-init
    entrypoint:
      - /bin/sh
      - -c
    command: ["ln -sf /mysql-init/init-user.sql /docker-entrypoint-initdb.d/init_user.sql \
      && docker-entrypoint.sh mysqld --init-file /mysql-init/unlock-change-log.sql --disable-log-bin"]
    expose:
      - "3306"
    restart: unless-stopped
  cromwell:
    depends_on:
      - "mysqldb"