apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mysqldb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: {{ .Values.db.name }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.db.password }}
          image: {{ .Values.images.mysql }}
          name: mysqldb
          stdin: true
          tty: true
          ports:
            - containerPort: {{ .Values.db.port }}
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldb-data-claim
            - mountPath: /configuration
              name: configuration-claim1
      restartPolicy: Always
      volumes:
        - name: mysqldb-data-claim
          persistentVolumeClaim:
            claimName: mysqldb-data-claim
        - name: configuration-claim1
          persistentVolumeClaim:
            claimName: configuration-claim1
status: {}
