# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# build runtime image
FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /app
COPY . ./
RUN apt update && apt full-upgrade -y && apt autoremove -y
ENTRYPOINT ["dotnet", "TriggerService.dll"]