// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/*
 * Task Execution Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;

namespace TesApi.Models
{
    /// <summary>
    /// TaskLog describes logging information related to a Task.
    /// </summary>
    [DataContract]
    public partial class TesTaskLog : IEquatable<TesTaskLog>
    {
        /// <summary>
        /// Logs for each executor
        /// </summary>
        /// <value>Logs for each executor</value>
        [DataMember(Name = "logs")]
        public List<TesExecutorLog> Logs { get; set; }

        /// <summary>
        /// Arbitrary logging metadata included by the implementation.
        /// </summary>
        /// <value>Arbitrary logging metadata included by the implementation.</value>
        [DataMember(Name = "metadata")]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// When the task started, in RFC 3339 format.
        /// </summary>
        /// <value>When the task started, in RFC 3339 format.</value>
        [DataMember(Name = "start_time")]
        public DateTimeOffset? StartTime { get; set; }

        /// <summary>
        /// When the task ended, in RFC 3339 format.
        /// </summary>
        /// <value>When the task ended, in RFC 3339 format.</value>
        [DataMember(Name = "end_time")]
        public DateTimeOffset? EndTime { get; set; }

        /// <summary>
        /// Information about all output files. Directory outputs are flattened into separate items.
        /// </summary>
        /// <value>Information about all output files. Directory outputs are flattened into separate items.</value>
        [DataMember(Name = "outputs")]
        public List<TesOutputFileLog> Outputs { get; set; }

        /// <summary>
        /// System logs are any logs the system decides are relevant, which are not tied directly to an Executor process. Content is implementation specific: format, size, etc.  System logs may be collected here to provide convenient access.  For example, the system may include the name of the host where the task is executing, an error message that caused a SYSTEM_ERROR state (e.g. disk is full), etc.  System logs are only included in the FULL task view.
        /// </summary>
        /// <value>System logs are any logs the system decides are relevant, which are not tied directly to an Executor process. Content is implementation specific: format, size, etc.  System logs may be collected here to provide convenient access.  For example, the system may include the name of the host where the task is executing, an error message that caused a SYSTEM_ERROR state (e.g. disk is full), etc.  System logs are only included in the FULL task view.</value>
        [DataMember(Name = "system_logs")]
        public List<string> SystemLogs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TesTaskLog {\n");
            sb.Append("  Logs: ").Append(Logs).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  Outputs: ").Append(Outputs).Append("\n");
            sb.Append("  SystemLogs: ").Append(SystemLogs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this, new JsonSerializerOptions { WriteIndented = true });
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == GetType() && Equals((TesTaskLog)obj);
        }

        /// <summary>
        /// Returns true if TesTaskLog instances are equal
        /// </summary>
        /// <param name="other">Instance of TesTaskLog to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TesTaskLog other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    Logs == other.Logs ||
                    Logs != null &&
                    Logs.SequenceEqual(other.Logs)
                ) &&
                (
                    Metadata == other.Metadata ||
                    Metadata != null &&
                    Metadata.SequenceEqual(other.Metadata)
                ) &&
                (
                    StartTime == other.StartTime ||
                    StartTime != null &&
                    StartTime.Equals(other.StartTime)
                ) &&
                (
                    EndTime == other.EndTime ||
                    EndTime != null &&
                    EndTime.Equals(other.EndTime)
                ) &&
                (
                    Outputs == other.Outputs ||
                    Outputs != null &&
                    Outputs.SequenceEqual(other.Outputs)
                ) &&
                (
                    SystemLogs == other.SystemLogs ||
                    SystemLogs != null &&
                    SystemLogs.SequenceEqual(other.SystemLogs)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Logs != null)
                {
                    hashCode = hashCode * 59 + Logs.GetHashCode();
                }

                if (Metadata != null)
                {
                    hashCode = hashCode * 59 + Metadata.GetHashCode();
                }

                if (StartTime != null)
                {
                    hashCode = hashCode * 59 + StartTime.GetHashCode();
                }

                if (EndTime != null)
                {
                    hashCode = hashCode * 59 + EndTime.GetHashCode();
                }

                if (Outputs != null)
                {
                    hashCode = hashCode * 59 + Outputs.GetHashCode();
                }

                if (SystemLogs != null)
                {
                    hashCode = hashCode * 59 + SystemLogs.GetHashCode();
                }

                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(TesTaskLog left, TesTaskLog right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TesTaskLog left, TesTaskLog right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
