apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ubuntu
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ubuntu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          resources: {}
      restartPolicy: Always
status: {}