apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cromwell
  name: cromwell
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cromwell
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cromwell
    spec:
      containers:
        - args:
            -  java -Djava.io.tmpdir=/cromwell-tmp/ -Dconfig.file=/configuration/cromwell-application.conf -jar /app/cromwell.jar server
          command:
            - /bin/sh
            - -c
          image: broadinstitute/cromwell:70
          name: cromwell
          stdin: true
          tty: true
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /cromwell-tmp
              name: cromwell-tmp-claim
      restartPolicy: Always
      volumes:
        - name: cromwell-tmp-claim
          persistentVolumeClaim:
            claimName: cromwell-tmp-claim
status: {}
