apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb-data-claim
  name: mysqldb-data-claim
spec:
  storageClassName: managed-standard-no-caching
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
status: {}
