apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: tes
  name: tes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tes
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tes
    spec:
      containers:
        - env:
          image: mcr.microsoft.com/cromwellonazure/tes:2
          name: tes
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
      restartPolicy: Always
      volumes:
status: {}
