apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: triggerservice
  name: triggerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: triggerservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: triggerservice
    spec:
      containers:
        - env:
          image: mcr.microsoft.com/cromwellonazure/triggerservice:2
          name: triggerservice
          resources: {}
      restartPolicy: Always
status: {}
