# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Restore packages in separate layer
COPY TesApi.Web/TesApi.Web.csproj TesApi.Web/
COPY Tes/Tes.csproj Tes/
COPY Common/Common.csproj Common/
RUN dotnet restore TesApi.Web/TesApi.Web.csproj

# Copy the rest of the files and publish
COPY . ./
RUN dotnet publish -c Release -o out --no-restore TesApi.Web/TesApi.Web.csproj

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
RUN apt update && apt full-upgrade -y && apt autoremove -y
RUN apt install -y postgresql-client
RUN adduser --home /home/tes -u 1000 tes
RUN apt install -y libcap2-bin
RUN setcap CAP_NET_BIND_SERVICE=+eip /usr/share/dotnet/dotnet
ENTRYPOINT ["dotnet", "tesapi.dll"]
