# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Restore packages in separate layer
COPY TesApi.Web/TesApi.Web.csproj TesApi.Web/
COPY Tes/Tes.csproj Tes/
COPY Common/Common.csproj Common/
RUN dotnet restore TesApi.Web/TesApi.Web.csproj

# Copy the rest of the files and publish
COPY . ./
RUN dotnet publish -c Release -o out --no-restore TesApi.Web/TesApi.Web.csproj

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "tesapi.dll"]
