# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY . ./
ENTRYPOINT ["dotnet", "tesapi.dll"]
