name: Format check on push
on: push
jobs:
  dotnet-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.100
     
    - name: dotnet tool restore
      run: dotnet tool restore

    - name: dotnet format
      run: dotnet format --verify-no-changes
