name: Format check on push
on: push
jobs:
  dotnet-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses:  actions/setup-dotnet@v3
     
    - name: dotnet tool restore
      run: dotnet tool restore

    - name: dotnet format
      run: dotnet format --verify-no-changes
