name: Format check on pull request
on: pull_request
jobs:
  dotnet-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Run dotnet format
        shell: bash
        run: |
          allProjectFiles=$(find ./ -type f -name "*.csproj" | tr '\n' ' ');
          if [ $? -ne 0 ]; then exit 1; fi
          echo "$allProjectFiles"
          for file in $allProjectFiles; do
              dotnet format $file --verify-no-changes --verbosity detailed
          done
